#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCALA_VERSION=`scala -e "print(scala.util.Properties.versionString)" | sed "s/version //" | sed "s/-.*//"`
CLASSPATH="${SCRIPT_DIR}/target/scala-${SCALA_VERSION}/classes"

if (! [ -e $CLASSPATH ]); then 
  SCALA_VERSION=`echo $SCALA_VERSION | sed 's/\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
  CLASSPATH="${SCRIPT_DIR}/target/scala-${SCALA_VERSION}/classes"
fi

FOUND_CONFIG="no"

for arg in $@; do
  case "$arg" in
    -f) FOUND_CONFIG="yes" ;;
    --config) FOUND_CONFIG="yes" ;;
  esac
done

CONFIG=""

if [ $FOUND_CONFIG = "no" ] ; then
  CONFIG="-f ${SCRIPT_DIR}/config/sourceSink.xml"
fi 

scala -cp $CLASSPATH -J-Xmx1024m com.ucombinator.dalvik.Analyzer $CONFIG $@
